### ISSUE TITLE
Can you publish a new release? 

### ISSUE THREAD

**Issue by DeflateAwning** [SnakePin/open-serial-port-monitor#1]

**Comment by DeflateAwning** [comment]
Hey, love this program. Are you able to tag a new release and publish the build?

**Comment by snake-4** [comment]
> Hey, love this program. Are you able to tag a new release and publish the build? 

Sorry, I almost forgot about this. I'll publish a build today.

**Comment by snake-4** [comment]
It is done. Sorry for keeping you waiting for too long.

**Comment by snake-4** [comment]
@DeflateAwning Can you tell me if the new build is working fine or not?

**Comment by DeflateAwning** [comment]
Am getting a virus warning. Can you upload the EXE to the release instead of a zip?

**Comment by snake-4** [comment]
> Am getting a virus warning. Can you upload the EXE to the release instead of a zip?

Done.

**Comment by DeflateAwning** [comment]
[This release](https://github.com/snake-4/open-serial-port-monitor/releases/tag/v1.0.8714.10462) gives an error: "At least one object must implement IComparable." Does it run for you?

**Comment by snake-4** [comment]
> [This release](https://github.com/snake-4/open-serial-port-monitor/releases/tag/v1.0.8714.10462) gives an error: "At least one object must implement IComparable." Does it run for you?

That's strange because it works for me. Can you tell me the steps to reproduce that error? Also the full error message if possible?

**Comment by DeflateAwning** [comment]
1. Open exe file on Windows 10
2. See error in popup message box.

That is the full error.

I bet a runtime or something isn't included in the exe

**Comment by snake-4** [comment]
> 1. Open exe file on Windows 10
> 2. See error in popup message box.
> 
> That is the full error.
> 
> I bet a runtime or something isn't included in the exe

Sorry, I figured the issue now, fixed it and fixed some other problems with the original repo. Everything should be working now!
